services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/irmafiguero199/laravel
    branch: 12.x
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
    dockerContext: .
    dockerfilePath: Dockerfile
